### ISSUE TITLE
Mark app as unmaintained in F-Droid + repository

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Camera-Abandoned#311]
As I needed to hear in https://github.com/SimpleMobileTools/Simple-Camera-Abandoned/issues/310 this app is unmaintained and I am really sorry to hear that, but anyway I appreciate the work you've put into it. So let's "bury" it properly…

First of all, you should mark teh app as unmaintained on the app stores. I am not that familiar with F-Droid internals [but I found this doc](https://f-droid.org/en/docs/How_to_Help/#add-information-about-no-longer-maintained-apps), which states you should just add a sentence at the beginning of the description and possibly some other metadata.
I thought you could also trigger that the app could be archived (moved to the archive repo), but that may happen automatically after some time, anyway/maybe cannot or should not be triggered before.

You can also [archive this repository](https://docs.github.com/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/archiving-repositories), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Edit:** Oh lol, sorry, just now I saw you renamed the repo to "[Abandoned](https://github.com/SimpleMobileTools/Simple-Camera-Abandoned)". Unfortunately, even though that should not be hard to miss, I missed it. :upside_down_face: Anyway, I guess the steps above should make an abandoned state more clear and also prevent opening new issues etc.

**Comment by tibbi** [comment]
Camera and Clock already has the abandonment note at the top of their descriptions

**Comment by rugk** [comment]
Ah cool okay. So what about archiving this repository?

**Comment by tibbi** [comment]
you can still download that app, it just wont be updated

**Comment by rugk** [comment]
Yes, you can download it, but what does this have to do with the git repository? As said, you could archive this here on GitHub, so you won't get annoyed by issues etc.

**Comment by tibbi** [comment]
nah, I can keep it open in case someone wants to fix something :)
