### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by ccoenen** [SimpleMobileTools/Simple-Camera-Abandoned#315]
GitHub has a feature to mark a repository as an archived project. This adds a yellow stripe at the top of the project and also makes the issue tracker read-only

![grafik](https://user-images.githubusercontent.com/124909/172055188-b26ba08f-33ae-4183-9529-e9769b9d1c9b.png)

**Comment by tibbi** [comment]
its not needed, we are rebuilding the app from scratch to reenable it at least on Android 10+
