### ISSUE TITLE
Update infos on the F-Droid app ?

### ISSUE THREAD

**Issue by Ugau943** [SimpleMobileTools/Simple-Camera-Abandoned#317]
Hem, I don't know if it's only for me, but on the F-Droid app, the presentation of the Simple Camera app is not up to date. The depreciation mention is not there. So I installed the app blindly, and missed some great photos! Just kidding, but I think it should be updated.

My F-Droid application and the repositories are all up to date.

On the website ([f-droid.com](https://f-droid.org/packages/com.simplemobiletools.camera/)) everything is correct.  

---
<img src="https://user-images.githubusercontent.com/48393457/173356076-c6c36f58-cd88-4d42-8e28-929776bb721a.jpg" width="300">

**Comment by tibbi** [comment]
Hi, the app is being rewritten from scratch, it will eventually be available again from Android 10 or so.
